### ISSUE TITLE
Duration and start/end times edit view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1053]
- [x] This view is for both: editing start/end times and duration at the same time.
- [x] The wheel is always draggable from both ends in order to change the start and stop times. Note that duration changes as well when dragging either start or stop handler.
- [x] When user starts dragging in the dark grey area of the circle (the area between two handles), then it moves both start and end times but duration remains the same.
- [x] For entries longer than 12h, user can spin the circle over itself over and over again. In that case, we can allow 999h duration, too.
*When an entry is more than 12 hours long, then both handles are still draggable. A user can spin full circles forward and backwards to increase or decrease a duration.*
- [x] Both start and end times are tappable and will open default iOS date-time picker. The content below will be pushed out as the picker appears.
- [ ] User can scroll the card's content: Only picker and the wheel will scroll.
- [x] To close a picker, user have to tap again on a start/end time.
- [x] Changing the picker, updates the wheel and vice versa.
- [x] While editing start/stop time/date by using the picker, automatically updates date and time above as well.
- [x] When user is editing stopped time entries, allow editing both start and stop times.
- [x] When user is editing currently running time entry, display 'Set' in end time field.
- [x] When user is editing currently running time entry, show ticking timer inside the circle.
- [x] When user is editing currently running time entry, do not allow dragging end time handle or the dark grey area of the circle.
- [x] When user taps 'Set', set end time for that time entry. End time should be the current time.
- [x] Include vibration feedback in the wheel for every 5 mins.
- [x] When a time entry is so short that two circles are overlapping, then start time handler should be on top.

### 24hour and 12hour clock examples when editing already stopped time entry
![toggl - ios - start-end times 24hour 1x](https://user-images.githubusercontent.com/5064445/34677939-5ea88f28-f49a-11e7-95d5-466d186702ea.png) ![toggl - ios - start-end times 12hour 1x](https://user-images.githubusercontent.com/5064445/34677944-6171aa46-f49a-11e7-9573-6bc2c8f19db1.png)

Zeplin: https://zpl.io/aBw0d8L & https://zpl.io/bWQxmEM

### Editing running time entry
![toggl - ios - start-end times running timer 1x](https://user-images.githubusercontent.com/5064445/34677968-74e5ae1a-f49a-11e7-9d0e-9d03da913682.png) ![toggl - ios - start-end times running timer v2 1x](https://user-images.githubusercontent.com/5064445/34678077-b904bb40-f49a-11e7-9725-55c7a330c12c.png)

Zeplin: https://zpl.io/2ZqNmKw

### Date/time picker
![toggl - ios - start-end times 24hour date and time picker 1x](https://user-images.githubusercontent.com/5064445/34678102-c62640dc-f49a-11e7-90d7-0fe2fe2dac77.png)

Zeplin: https://zpl.io/ad9Np41

### Overlapping handlers
![toggl - ios - start-end times 24hour overlapping 1x](https://user-images.githubusercontent.com/5064445/34678122-d3845124-f49a-11e7-9b76-46e6e85ae9b6.png)

Zeplin: https://zpl.io/bez7kMm

**Comment by amulware** [comment]
This needs designs for how it looks when the time entry is so short that the two circle-handles are touching/overlapping, as well as when the time slot is almost 12 hours, and the two circles overlap that way, and if it is more than 12 hours, or even multiple days long. Also, if the entry is more than 12 hours, can both handles still be dragged? How does this work?

**Comment by pe0ny** [comment]
- When a time entry is so short that two circles are overlapping, then start time handler should be on top. *I'll make a screen for that, too.*
- When an entry is more than 12 hours long, then both handles are still draggable. A user can spin full circles forward and backwards to increase or decrease a duration.

**Comment by amulware** [comment]
If the time entry is tiny, and you want to make it bigger by dragging the handles, is it not more natural to drag the stop time, hence that should be on top? Or what is your reasoning for the other way around?

**Comment by pe0ny** [comment]
My reasoning is that I never ever change stop time. Also, when you forgot to start a timer, you start it and then want to change the start time, eg add 10-30min.

**Comment by pe0ny** [comment]
### A short time entry and two overlapping circles (start handler on the top)
![toggl - ios - start-end times 24hour overlapping 1x](https://user-images.githubusercontent.com/5064445/33878846-467a391c-df35-11e7-8bbe-c4e667a3f101.png)

Zeplin: https://zpl.io/bez7kMm

### A running time entry that was just started
![toggl - ios - start-end times running timer v2 1x](https://user-images.githubusercontent.com/5064445/33878863-506ca464-df35-11e7-81b1-e9257699658e.png)

Zeplin: https://zpl.io/Vxn5wgR

**Comment by ricotheque** [comment]
Just noting that the allowing 12+ hours will definitely help case/605797.

**Comment by simonrozsival** [comment]
How should the wheel and the modal view scale on different screen sizes?

**Comment by amulware** [comment]
Also, how will the dark gray area look for close to or longer than 12h durations? I think there needs to be some sort of drop shadow to indicate which of the handles are start or stop - I'm thinking like the ones on the apple watch activity rings.

**Comment by pe0ny** [comment]
@simonrozsival Let's keep it static.

**Comment by simonrozsival** [comment]
@pe0ny I didn't notice this comment and implemented scaling - http://prntscr.com/hz2uiy (SE vs Plus) - should I remove it?

**Comment by pe0ny** [comment]
@simonrozsival Oh, it's great! :) Of course, we won't remove it. Realy well done 🙌
