### ISSUE TITLE
New time entry UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1143]
- [x] Suggestion modes for time entries, projects, tasks and tags work the same way like on iOS.
- [x] Tapping projects or tags icon at the top right corner, opens projects/tags suggestion mode.
- [x] Tapping billable icon at the top right corner, sets (or removes) a billable flag to a time entry.
- [x] Back arrow takes the user back to the timer page and discards new time entry.
- [x] Tapping ticking duration opens expandable time/date edit. 
- ~Start/stop times and date use pickers like they do in edit view.~ On hold for the meantime
- [x] Green fab saves the changes and takes the user back to the timer page.

### New time entry
![new time entry](https://user-images.githubusercontent.com/5064445/33833361-1344f080-de88-11e7-913d-a00ad597edc3.png)

Zeplin: https://zpl.io/2Ed3ONx

### Time entry autocomplete
![new time entry autocomplete](https://user-images.githubusercontent.com/5064445/33833911-e0465a64-de89-11e7-9c18-4f398e1754df.png)

Zeplin: https://zpl.io/V4EXDmM

### Projects autocomplete
![new time entry - projects](https://user-images.githubusercontent.com/5064445/33833925-eaf2eb4e-de89-11e7-9dce-990bb9edeff0.png)

Zeplin: https://zpl.io/bAO38MO

### Tasks
![new time entry - projects and tasks](https://user-images.githubusercontent.com/5064445/33833947-fbd3352c-de89-11e7-89c2-2ef171d84fb5.png)

Zeplin: https://zpl.io/a30JpLl

### Expanded time/date edit
![date expanded](https://user-images.githubusercontent.com/5064445/33834159-c84013a0-de8a-11e7-89e1-a8cc8922bf0e.png)

Zeplin: https://zpl.io/VkKLDYg
