### ISSUE TITLE
EPIC: Gain/lose/no workspaces

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2593]
Opening this to replace #1336

This is an overview of work to be done. I'll try and cover as much as I can with smaller issues, but if I miss anything, please feel free to let me know or fill the gaps yourself.

- [ ] #2627 If we are not yet doing so, we should always pull ALL workspaces on every sync so that we can compare the list with the local one.

When persisting that full list we should compare it to the list of local workspaces, and where they differ resolve conflicts accordingly, IN THIS ORDER:

If we lose access:
- [ ] #2628 detect the same
- [ ] #2631 remove all synced TEs from the database
- [ ] remove all synced projects/clients/tags that are not referred to by any TE (clients are referred through the projects and their check is maybe a special case)
- [ ] #1337 mark all remaining (i.e. unsynced) entities especially, so that they cannot show up in auto-completion, suggestions. TEs like that should not be able to be continued either

If we gain access to a new WS:
- [ ] add that workspace to the DB
- [ ] make sure that if we had access to this WS before, and there is unsynced data, all that can sync again (we may need to undo whatever we did to them in #1337), and that data is merged correctly when pulling
- [ ] then reset all ?since dates to null
- [ ] go to the top of the pull sync (which will automatically fetch all data for those workspaces, and also for other workspaces, but that's something to optimise later if we need to) - this prevents the stuff from below from running until after the full pull

If the user has no workspaces:
- [ ] #2592 check this by looking if the database has any non-ghost (#1337) workspaces, it does not matter if they are synced or not
- [ ] #2334 throw an exception and halt syncing if this happens - the exception will cause a prompt making the user create or retry sync (and the retry will cause another exception if nothing has changed; if it completes however without throwing that exception, the prompt closes)
- [ ] note that the other three overlays (410, 418 and 403(401?)) have priority over this one, and if a (retried) sync causes them, their respective overlay should be shown, and not this one

Further:
- [ ] on app start/activation(every X minutes? - depending on the cost of this operation) all 'invalid' entities that are no longer referred to by any time entries can be removed (alternatively, when TEs are edited/deleted, but that might be more complicated?)

**Comment by amulware** [comment]
@juanlaube and I discussed internally, that since every entity keeps a reference to their workspace, which is fetched at the same time, we could just store the ghost flag only on the workspace, and not all entities. That might simplify things a lot, (probably at the cost of a tiny bit of performance for most database accesses).

**Comment by amulware** [comment]
🦅
