### ISSUE TITLE
Improve the Login-related event tracking

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#3898]
🔑 Related to `user-access-improvements` project.

This is the full list of events that need to be tracked.

* [ ] ⚡ Successful login (with information about login type: email/google)
* [ ] ⚡ Failed login (with a HTTP code error)
* [ ] ⚡ Attempt to login with an invalid email/password combination
* [ ] ⚡ Request to reset password
* [ ] ⚡ 3rd failed operation (regardless of whether the data entered is unchanged)
* [ ] ⚡ Attempt to get help through the `I'm stuck` link
* [ ] ⚡ A number of returns to the `Email` _screen_ after the `Password` _screen_ has been opened, tracked at the moment of login.

If anything is not completely clear, please ask in the comments. Also, think about the ideas yourself and maybe even start with a suggestion of your own.

📃 Not all events have to be solved in the same PR. Some events require view model to be done. Others require just the `UserAccessManager`.
