### ISSUE TITLE
Improve the Signup-related event tracking

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#3899]
🔑 Related to `user-access-improvements` project.

This is the full list of events that need to be tracked.

* [ ] ⚡ Successful signup
* [ ] ⚡ Failed signup (with a HTTP code error)
* [ ] ⚡ Opening Terms of Service or Privacy Policy, along with the duration spent on those pages
* [ ] ⚡ Country is not set at the time of opening the `Country Selection/ToS/PP` _screen_.
* [ ] ⚡ Manual changes to the country (not opening the window, just **changes**)
* [ ] ⚡ Attempt to get help through the `I'm stuck` link
* [ ] ⚡ A number of returns to the `Email` _screen_ after the `Password` _screen_ has been opened, tracked at the moment of signup.

If anything is not completely clear, please ask in the comments. Also, think about the ideas yourself and maybe even start with a suggestion of your own.

📃 Not all events have to be solved in the same PR. Some events require view model to be done. Others require just the `UserAccessManager`.
