### ISSUE TITLE
The MVP Calendar Component for Android

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4242]
In theory, this view should offer the same functionality as the iOS, with varying design based and android implementation details.
The calendar itself will be composed of multiple issues for each of its parts
These issues will be added after further investigation.

We'll have an MVP of the Calendar component for android when we have these issues done:
- [x] The calendar layout manager #4284 
- [x] The calendar recycler view #4282 
- [x] The calendar events adapter #4285

I expect this to be done after #4291 and have the all the related bindings added to the fragment, that is, show the events, clicking events to open the edit time entry activity, create time entries from the calendar..

**Comment by daividssilverio** [comment]
Closed by #4284 #4282 #4285
