### ISSUE TITLE
Push time entries to backend

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#452]
At first, pushing time entries will be enough since that is the only thing the app can create for now.

The general steps are:

- [x] checking if any time entries have to be synced, and returning the oldest of them #497
- [x] try syncing this entry #498
  - [x] on success, use conflict resolution to persist return value from API #498
  - [x] on failure, mark entry as unsyncable (needs changes to database models) and don't try syncing it again until user changes it #496
  - [ ] (optional) ~~if failure is server/connection error, enter proper retry loops (refer to internal designs and documentation)~~  (we'll do this later)

**Comment by simonrozsival** [comment]
Do we necessarily want to return the _oldest_ time entry to be synced? Isn't it sufficient to return _some_ time entry, since all of the entries will be processed eventually?

**Comment by amulware** [comment]
I'd prefer syncing from oldest to newest. That's more predictable, and if only some data is synced every time the user opens the app, this will prevent data from becoming very old.
