### ISSUE TITLE
Test 1.12 - Argon

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4769]
# 🐧 Manual Test Template

## Testing sign in area ##

- [x] Test standard email and password sign in
- [x] Test standard email and password sign in with invalid email address
- [x] Test standard email and password sign in with invalid password
- [x] Test signup with standard email and password
- [x] Test terms and conditions link
- [x] Test privacy policy link
- [x] Test signin with Google signin
- [ ] Test signup with Google signin
- [x] Test forgotten password link
- [x] Test forgotten password link with invalid email
- [x] Is country selection automatically selecting the right country?
- [x] Is country selection allowing manual selection
- [x] Test email field with invalid email
- [x] Test email field with mixed character sets (including various languages)
- [x] Test password field for old/changed password

## Testing timer page
- [x] Start timer
- [x] Stop timer
- [x] Enter description
- [ ] Add new project
- [ ] Add new client
- [ ] Add new tag
- [x] Add long (3000 characters) description and confirm character limit error shows in the edit view after sync
- [ ] Add new project using existing client
- [x] Add existing project
- [x] Add existing tag
- [x] Start new timer, select no project, stop
- [x] Create new manual time entry
- [x] Start a new entry, add multiple tags.
- [x] Start a new entry, discard new entry.
- [x] Continue an entry
- [x] Delete an entry

## Testing editing time entry
- [x] Change description
- [x] Change project
- [x] Remove project
- [x] Change tags
- [x] Remove tags
- [x] Change start time with the barrel/manual selection
- [x] Change start time with the wheel
- [x] Change end time with barrel/manual selection
- [x] Change start date
- [x] Change end date
- [ ] Change duration
- [x] Change date from main entry page
- [x] Discard changes to entry
- [x] Delete entry from edit view
- [x] Confirm changes
- [x] Create new project from edit view
- [x] Create new client from edit view
- [x] Create new tag from edit view

## Testing report screen
- [x] Custom range
- [x] Is correct data displayed
- [x] Are categories displaying correct timerframe and dates?
- [x] Is web displaying the same data?
- [x] Today
- [x] Yesterday
- [x] This year
- [x] This month
- [x] Last month
- [x] This week
- [x] Last week
- [x] Custom range 1 year
- [x] Custom range 1 month
- [x] Custom range 1 week
- [x] Custom range 1 day
- [x] Ensure correct year is selected on all options
- [x] Change workspaces

## Testing settings page
- [x] Sign out normal email
- [x] Sign out google sign in
- [x] Change workspace
- [x] Date format MM/DD/YYYY
- [x] Date format DD-MM-YYYY
- [x] Date format MM-DD-YYYY
- [x] Date format YYYY-MM-DD
- [x] Date format DD/MM/YYYY
- [x] Date format DD.MM.YYYY
- [x] 24 hour time format
- [x] 12 hour format
- [x] Duration format Classic
- [x] Duration format Improved
- [x] Duration format Decimal
- [x] First day of the week Monday
- [x] First day of the week Tuesday
- [x] First day of the week Wednesday
- [x] First day of the week Thursday
- [x] First day of the week Friday
- [x] First day of the week Saturday
- [x] First day of the week Sunday
- [x] Manual mode
- [x] Submit feedback
- [x] About
- [x] Help
- [ ] Is "Synced" displaying correctly?

## Testing Calendar Integration
- [x] Are calendar entries showing correctly?
- [x] Create an entry from a calendar entry
- [x] Adjust the start time
- [x] Adjust the end time

## Testing Siri Integration
- [x] Start a time entry
- [x] Stop a time entry

## Multiple Workspaces
- [x] Switch workspaces
- [x] Go offline then switch workspaces (Airplane mode)
- [x] Switch between workspaces while timer running
- [x] Is data displaying correctly in web?
- [x] Force sync then switch
- [x] Leave a workspace
- [x] Be removed from a workspace while offline
- [x] Be removed from a workspace with an active entry running

## Testing Interactions/Sync between this app and others
- [x] Edit client on web whilst mobile online
- [x] Delete client on web whilst mobile online and tracking a task
- [x] Edit client on web whilst mobile online and tracking a task
- [x] Tags
- [x] Archiving
- [x] Create new project on web whilst mobile offline
- [x] Tasks
- [x] Try creating new entries on web whilst mobile offline
- [x] Edit client on web whilst mobile offline
- [x] Try stopping timer on web while mobile offline
- [x] Delete project on web whilst mobile offline
- [x] Make changes to projects on web

## Testing in different timezones

- [ ] Check

## Testing onboarding

- [x] Check

## Test that the UI is appearing as intended and report any issues

- [x] Check

## Release specific:

- [x] The app should no longer crash when opening the settings without having an avatar (#4553)
- [x] The calendar view. Let's give it another basic rundown to make sure there's no regression

Note that this release contains significant refactoring to several parts of the app. We need to test everything thoroughly to ensure we didn't introduce bugs.

Fixes of things found during testing:
- [x] Crashing when I click on 23 in reports #4779
- [x] Inverted positions of duration and date labels #4789
- [x] Occasional crashes after starting a time entry immediately after signup. #4785
- [x] Date range selection in reports showing wrong month. #4429
- [x] Duration isn't changing if manually typed and saved #4799
- [x] Start time entry time entry suggestions don't display the right project color #4797
- [x] Trying to create a project or tag isn't showing the create project or tag prompt #4798
- [ ] Time entries not stopping correctly after coming back online #4817
- [ ] Workspaces not changing correctly on settings page #4815
- [ ] Empty state view is visible after creating first time entry #4820
- [x] + and play icon not appearing after switching to manual mode #4801

**Comment by amulware** [comment]
Release PR: https://github.com/toggl/mobileapp/pull/4768

**Comment by ApocalypticFish** [comment]
I'm holding testing for now until I can check this tomorrow with @amulware as I'm seeing a lot of crashes.

**Comment by amulware** [comment]
I added more checks from the issues found during testing so far above.

**Comment by ApocalypticFish** [comment]
This one has taken much longer than I was expecting as there have been more issues than I'd anticipated. I've added a few more now and will try to complete this tomorrow, but I do want to take some more time with the calendar integration as it's new and was intending to before these other issues.

**Comment by ApocalypticFish** [comment]
Just waiting for the next release candidate now

**Comment by amulware** [comment]
Updated list of things to test with further issues again.

**Comment by amulware** [comment]
All found bugs have been fixed. Please verify this in the upcoming build.

**Comment by ApocalypticFish** [comment]
🖖

**Comment by ApocalypticFish** [comment]
So completed some tests, blank entries still seem to be created in the default workspace rather than the selected workspace in settings. But I think this requires further investigation.

Also noted a bit of a delay when creating projects and tags, this seem increased when offline

**Comment by amulware** [comment]
Been recommended internally to go ahead with the release and am releasing to first users now.
