### ISSUE TITLE
Create a checklist for reviewers

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#72]
This could also be the default PR template so people remember to check it themselves when creating the PR. Some of it can be enforced by #38, so please correct me if I'm wrong.

So far we have:

- [ ] Check classes' access modifiers
- [ ] Check indenting (spaces vs tabs)
- [ ] Check property naming
- [ ] Make sure PR includes relevant tests
- [ ] Run Integration Tests

**Comment by amulware** [comment]
This seems to imply that integration tests should run for every single PR. Is that the intent? I am concerned that the tests will take so long it will significantly slow down reviewing.

Also why property naming specifically, and not naming in general?

**Comment by willsb** [comment]
This proved unnecessary
